# Generated by Django 4.2.24 on 2025-10-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work08', '0002_remove_memo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memo_images/'),
        ),
    ]
