"""
Django settings for python_apps_django project.

Generated by 'django-admin startproject' using Django 4.2.24.
"""

from dotenv import load_dotenv
load_dotenv()

from pathlib import Path
import os
import dj_database_url

# ============================================================
# BASE
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-uo4)xlk)^l2ax&4y!1o*m*ofeq(hv*8)y53o&(h29%64mrlq$^'
DEBUG = True

# ============================================================
# HOSTS
# ============================================================
ALLOWED_HOSTS = (os.environ.get("ALLOWED_HOSTS") or "").split(",")
CSRF_TRUSTED_ORIGINS = (os.environ.get("CSRF_TRUSTED_ORIGINS") or "").split(",")

# ============================================================
# APPLICATIONS
# ============================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'work05',
    'work06',
    'work07',
    'work08',
    'work09',
    'work10',
    'sns',
]

# ============================================================
# MIDDLEWARE
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================
# URL / TEMPLATE
# ============================================================
ROOT_URLCONF = 'python_apps_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← 追加済み ✅
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'python_apps_django.wsgi.application'

# ============================================================
# DATABASE
# ============================================================
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASE_HOST = os.getenv("DB_HOST", "localhost")
    DATABASE_NAME = os.getenv("DB_NAME", "new_project_db")
    DATABASE_USER = os.getenv("DB_USER", "root")
    DATABASE_PASSWORD = os.getenv("DB_PASSWORD", "test")
    DATABASE_PORT = os.getenv("DB_PORT", "3306")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": DATABASE_NAME,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
        }
    }

# ============================================================
# PASSWORD VALIDATORS
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================================
# INTERNATIONALIZATION
# ============================================================
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True

# ============================================================
# STATIC & MEDIA
# ============================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================
# LOGIN / LOGOUT
# ============================================================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'work10:todo_list'
LOGOUT_REDIRECT_URL = 'login'

# ============================================================
# BASIC AUTH (optional)
# ============================================================
if os.environ.get("ENABLE_BASIC_AUTH") == "true":
    MIDDLEWARE.append("basicauth.middleware.BasicAuthMiddleware")
    BASICAUTH_USERS = {
        os.environ.get("BASIC_AUTH_USERNAME"): os.environ.get("BASIC_AUTH_PASSWORD"),
    }

# ============================================================
# DEFAULT FIELD
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
