# Generated by Django 4.2.24 on 2025-10-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work08', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='image',
        ),
    ]
